import Image from "next/image";
import { SectionHeading } from "./SectionHeading";

const organizationTiles = [
  { title: "Hospitals & Health Systems", description: "Become a participating site or host a longitudinal training program at your facility. We support onboarding, curriculum, and accreditation logistics.", action: "Learn how to join", image: "/reference/where-org-1.png", layout: "large" },
  { title: "Community Organizations", description: "Continuity clinics and federally qualified health centers bridging care where it matters most.", action: "Explore the model", image: "/reference/where-org-2.png", layout: "small" },
  { title: "Academic Institutions", description: "University affiliation and faculty appointment structures that align with residency standards.", action: "See requirements", image: "/reference/where-org-3.png", layout: "small" },
];

function OrganizationTile({ tile }: { tile: (typeof organizationTiles)[number] }) {
  const isLarge = tile.layout === "large";
  return <article className={`group relative isolate min-h-64 overflow-hidden rounded-xl bg-[#002c5b] text-white ${isLarge ? "md:row-span-2 md:min-h-[406px]" : "min-h-48"}`}><Image src={tile.image} alt="" fill className="-z-20 object-cover transition duration-500 group-hover:scale-105" sizes={isLarge ? "(max-width: 768px) 100vw, 55vw" : "(max-width: 768px) 100vw, 45vw"} /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-[#002c5b]/95 via-[#002c5b]/55 to-[#002c5b]/10" /><div className={`absolute inset-x-0 bottom-0 p-5 sm:p-6 ${isLarge ? "sm:p-7" : ""}`}><h3 className={`font-display font-bold uppercase leading-none ${isLarge ? "text-2xl sm:text-3xl" : "text-xl sm:text-2xl"}`}>{tile.title}</h3><p className={`mt-3 max-w-2xl text-xs leading-5 text-white/90 ${isLarge ? "sm:text-sm" : ""}`}>{tile.description}</p><a href="#contact" className="mt-4 inline-flex items-center gap-4 text-xs font-semibold capitalize text-white transition hover:text-[#f5c400]">{tile.action}<span className="text-xl leading-none transition-transform group-hover:translate-x-1">⟶</span></a></div></article>;
}
export function LocationsSection() {
  return <section id="locations" className="mx-auto max-w-7xl px-5 py-5 sm:py-20 lg:px-10 lg:py-18"><div className="max-w-4xl"><h2 className="font-display text-4xl font-bold uppercase leading-[0.95] text-[#002c5b] sm:text-5xl">Where does your<br className="hidden sm:block" /> organization fit in?</h2><p className="mt-5 max-w-5xl text-xs font-medium leading-5 text-slate-700 sm:text-sm">Every entry point into the program has a clear path. Choose the one that matches your setting.</p></div><div className="mt-9 grid gap-2 sm:gap-3 md:grid-cols-[1.08fr_0.92fr] md:grid-rows-2"><OrganizationTile tile={organizationTiles[0]} /><OrganizationTile tile={organizationTiles[1]} /><OrganizationTile tile={organizationTiles[2]} /></div><a className="mt-6 block rounded-xl border border-[#ead7da] bg-[#fcf4f5] p-5 text-[#002c5b] transition hover:border-[#c5222c] sm:p-7 lg:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><h3 className="font-display text-2xl font-bold uppercase leading-none sm:text-3xl">Developing a residency</h3><p className="mt-3 max-w-xl text-xs font-semibold leading-5 sm:text-sm">Understand what the accreditation process requires, how long each milestone takes, and what support is available from day one.</p></div><span className="flex shrink-0 items-center gap-4 text-xs font-bold capitalize">Get the full guide <span className="text-2xl font-normal">⟶</span></span></div></a></section>;
}
